### ISSUE TITLE
#2

### ISSUE THREAD

**Issue by battlealanna** [hydro-lab/Pittsburgh-Water-Changes#2]
Starting at line #98 I left some comments about the for loops. Lots of trial and error so far so I'm reviewing vids and stackoverflow. I'll still be playing around with it, but this is to keep you in the "loop."

**Comment by dmkahler** [comment]
"Loop"... nice.  I'll take a look.

**Comment by dmkahler** [comment]
I added some code around line 105.  Currently runs very slowly.  We should discuss parallelization.

```
cnt <- 0 # counting variable
for(i in 1:nrow(crp.chartier2009)){
     for(j in 1:ncol(crp.chartier2009)){
          if (is.na(crp.chartier2009[i,j])==FALSE) { # determines if the value is not NA
               if (crp.chartier2009[i,j]==1) { # sets impermeable value(s), add more here.
                    cnt <- cnt +1
               }
          }
     }
}
```

**Comment by dmkahler** [comment]
Fixed with command below, which pulled the data from the raster file (lost geographic data in process, but that's fine).  Since geographic data are gone, please use caution between the two different types of land cover datasets as they may have different resolutions.

```
img <- as.matrix(crp.chartier2009)
```

Now it uses the variable `img`.  Next, I will remove the extra lines and create an automation.
